# Generated by Django 5.0.4 on 2024-05-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
