# Generated by Django 5.0.4 on 2024-06-04 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_insta_link_product_material_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_img', to='store.productimage'),
            preserve_default=False,
        ),
    ]
