# Generated by Django 5.0.4 on 2024-06-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_images_remove_product_main_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='product_id',
        ),
    ]
