# Generated by Django 5.0.4 on 2024-06-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_product_productimage_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
    ]
