# Generated by Django 5.0.4 on 2024-06-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_productimage_is_main_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimagerelation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='productimagerelation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product', 'is_main'), name='unique_main_image'),
        ),
    ]
