# Generated by Django 5.0.4 on 2024-06-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_coupon_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
    ]
